language: elixir
elixir:
  - 1.4.0
  - 1.5.0
otp_release:
  - 18.2
  - 19.1
install:
  - mix local.hex --force
  - mix local.rebar --force
  - mix deps.get
  - MIX_ENV=test mix deps.compile
script:
  - mix test
after_script:
  - mix deps.get --only docs
  - MIX_ENV=docs mix inch.report
notifications:
  email:
    - fertapric@gmail.com
